output="infrastructure/database/sqlboiler/models"
add-global-variants=true
[mysql]
  dbname  = "test_database"
  host    = "localhost"
  port    = 3306
  user    = "docker"
  pass    = "docker"
  sslmode = "false"