// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Children", testChildren)
	t.Run("Persons", testPersons)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Children", testChildrenDelete)
	t.Run("Persons", testPersonsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Children", testChildrenQueryDeleteAll)
	t.Run("Persons", testPersonsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Children", testChildrenSliceDeleteAll)
	t.Run("Persons", testPersonsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Children", testChildrenExists)
	t.Run("Persons", testPersonsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Children", testChildrenFind)
	t.Run("Persons", testPersonsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Children", testChildrenBind)
	t.Run("Persons", testPersonsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Children", testChildrenOne)
	t.Run("Persons", testPersonsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Children", testChildrenAll)
	t.Run("Persons", testPersonsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Children", testChildrenCount)
	t.Run("Persons", testPersonsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Children", testChildrenHooks)
	t.Run("Persons", testPersonsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Children", testChildrenInsert)
	t.Run("Children", testChildrenInsertWhitelist)
	t.Run("Persons", testPersonsInsert)
	t.Run("Persons", testPersonsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("ChildToPersonUsingPerson", testChildToOnePersonUsingPerson)
	t.Run("PersonToUserUsingCreatedUser", testPersonToOneUserUsingCreatedUser)
	t.Run("PersonToUserUsingUpdatedUser", testPersonToOneUserUsingUpdatedUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PersonToChildren", testPersonToManyChildren)
	t.Run("UserToCreatedUserPersons", testUserToManyCreatedUserPersons)
	t.Run("UserToUpdatedUserPersons", testUserToManyUpdatedUserPersons)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("ChildToPersonUsingChildren", testChildToOneSetOpPersonUsingPerson)
	t.Run("PersonToUserUsingCreatedUserPersons", testPersonToOneSetOpUserUsingCreatedUser)
	t.Run("PersonToUserUsingUpdatedUserPersons", testPersonToOneSetOpUserUsingUpdatedUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PersonToChildren", testPersonToManyAddOpChildren)
	t.Run("UserToCreatedUserPersons", testUserToManyAddOpCreatedUserPersons)
	t.Run("UserToUpdatedUserPersons", testUserToManyAddOpUpdatedUserPersons)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Children", testChildrenReload)
	t.Run("Persons", testPersonsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Children", testChildrenReloadAll)
	t.Run("Persons", testPersonsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Children", testChildrenSelect)
	t.Run("Persons", testPersonsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Children", testChildrenUpdate)
	t.Run("Persons", testPersonsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Children", testChildrenSliceUpdateAll)
	t.Run("Persons", testPersonsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
